services:

  cliente_api_mrbot:
    container_name: abustosp/cliente_api_mrbot
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    networks:
      - nginx_default

networks:
  nginx_default:
    external: True
