services:

  cliente-api-mrbot:
    image: abustosp/cliente-api-mrbot
    container_name: cliente-api-mrbot
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    # volumes:
    #   - ./:/app
    networks:
      - nginx_default

networks:
  nginx_default:
    external: True
